### ISSUE TITLE
Template option values can't be '0'.

### ISSUE THREAD

**Issue by coreequip** [impresspages/ImpressPages#591]
When a template option's value is '0' the less-variable is skipped. The result is, the compiler acts as the template variable never exists (or is not defined). The is normally no problem, because its just creates "invalid" CSS code. But it is compileable by the less compiler.

But when you use less-functiones (ex. `unit`) then a parameter is missing.

The `theme.json`:

``` javascript
{
    "label": "Border-Radius",
    "name": "borderRadius",
    "type": "text",
    "default": "0"
}
```

The less-file:

``` less
.mySpecialBorderRadius {
    border-radius: unit(@borderRadius, px)
}
```
